name: Cloudfox
favicon: null
layout_spectrum: 0.04476823634468019
typography_spectrum: 0.9652355823200196
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5729068093933165
  lightness: 0.9894894019234926
  saturation: 0.05010918923653662
  rhythmicContrast: 0.6546024214476347
purpose: []
